version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 1323:1323
    volumes:
      - ./db:/db

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

#   migrate:
#     image: migrate/migrate
#     # networks:
#     #   - new
#     volumes:
#       - migrations:/migrations
#     command:
#       [
#         "-path",
#         "/migrations",
#         "-database",
#         "./data/db/processes.db",
#         "up",
#         "3",
#       ]
#     depends_on:
#       - backend

volumes:
  migrations:
