version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 1323:1323

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      - VITE_API_HOST=localhost:1323/api/v1
    depends_on:
      - backend

volumes:
  migrations:
